# Generated by Django 5.1.2 on 2024-11-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='blog Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
